// front-end-vue/src/components/DateInput.vue
<template>
  <div>
    <slot></slot>
    <span class="label" :class="{ 'label-my-success': value, 'label-my-error': !value }">
      {{ formatDate1 }}
    </span>
    <input ref="textInput" :id="id" @input="updateDate($event.target.value)"
           placeholder="Enter date in free format..." class="form-control">
  </div>
</template>

<script>
  export default {
    props: ['value', 'id'],
    computed: {
      formatDate () {
        const months = [
          'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
          'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'
        ]
        const year = this.value.getFullYear()
        const month = this.value.getMonth()
        const day = this.value.getDate()
        return `${months[month]} ${day}, ${year}`
      },
      formatDate1 () {
        if (!this.value) return 'Invalid Date'
        return this.formatDate
      },
      formatDate2 () {
        if (!this.value) return null
        return this.formatDate
      }
    },
    mounted () {
      this.$refs.textInput.value = this.formatDate2
    },
    methods: {
      updateDate (value) {
        const test = new Date(value)
        const date = test.toJSON() ? test : null
        this.$emit('input', date)
      }
    }
  }
</script>

<style scoped>
  .label {
    padding-top: .3em !important;
    border-radius: .4em !important;
  }
  .label-my-success {
    background-color: #008000;
  }
  .label-my-error {
    background-color: #a94442;
  }
</style>

// front-end/src/app/customization/date-input.component.ts
import { Component, forwardRef } from '@angular/core';
import { ControlValueAccessor, NG_VALUE_ACCESSOR } from '@angular/forms';

const noop = () => {};

const DATE_INPUT_CONTROL_VALUE_ACCESSOR = {
    provide: NG_VALUE_ACCESSOR,
    useExisting: forwardRef(() => DateInputComponent),
    multi: true
};

@Component({
    selector: 'my-date-input',
    template: `
        <label for="completed">
            Completed on
            <span class="label label-default">{{formatDate()}}</span>
        </label>
        <input [(ngModel)]="value" placeholder="Free date format" class="form-control">
    `,
    providers: [DATE_INPUT_CONTROL_VALUE_ACCESSOR]
})
export class DateInputComponent implements ControlValueAccessor {
    private innerValue = '';
    private bindValue: Date;

    private onTouchedCallback: () => void = noop;
    private onChangeCallback: (_: any) => void = noop;

    get value(): any {
        return this.innerValue;
    };

    set value(v: any) {
        if (v === this.innerValue) return;
        this.innerValue = v;
        const test = new Date(v);
        this.bindValue = test.toJSON() ? test : null;
        this.onChangeCallback(this.bindValue);
    }

    writeValue(value: any) {
        if (!value) return;
        this.bindValue = value;
        this.innerValue = this.formatDate();
    }

    registerOnChange(fn: any) {
        this.onChangeCallback = fn;
    }

    registerOnTouched(fn: any) {
        this.onTouchedCallback = fn;
    }

    /*
    * TO DO: Move to a service.
    */
    formatDate() {
        const months = [
            'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
            'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'
        ];
        if(!this.bindValue) return null;
        const year = this.bindValue.getFullYear();
        const month = this.bindValue.getMonth();
        const day = this.bindValue.getDate();
        return `${months[month]} ${day}, ${year}`;
    }
}
