// front-end-vue/src/components/ItemList.vue
<template>
  <div>

    <modal ref="deleteConfirm" @close="closeConfirm">
      <div slot="header"><h4>{{ removeHeader }}</h4></div>
      <div slot="body">
        Are you sure you want to remove <span class="badge">{{ itemTitle }}</span>?
      </div>
    </modal>

    <div class="my-search input-group">

        <input type="text" class="form-control"
               ref="search"
               :placeholder="searchPlaceholder"
               :value="filter"
               @keyup.enter="applySearch"
               @keyup.esc="clearSearch">

        <div class="input-group-btn">

          <a @click="applySearch" class="btn btn-default" title="Apply Search Filter">
            <i class="glyphicon glyphicon-search"></i>
          </a>

          <a @click="clearSearch" class="btn btn-default" title="Clear Search Filter">
            <i class="glyphicon glyphicon-remove-sign"></i>
          </a>

          <router-link v-if="my" to="new" append class="btn btn-default" :title="addPrompt">
            <i class="glyphicon glyphicon-plus"></i>
          </router-link>

          <a @click="download" class="btn btn-default" :title="downloadPrompt">
            <i class="glyphicon glyphicon-download"></i>
          </a>

          <label v-if="my" for="file" class="btn btn-default" :title="uploadPrompt">
            <i class="glyphicon glyphicon-upload"></i>
          </label>

        </div>
    </div>

    <form ref="uploadForm">
      <input type="file" id="file" @change="uploadChange">
    </form>

    <div class="panel panel-default">
      <slot></slot>
    </div>

    <pager :frame="8"
           :pageCount="pageCount"
           :page="page"
           @change="changePage">
    </pager>

  </div>
</template>

<script>
  import Pager from './Pager'
  import Modal from './Modal'
  import { mapGetters, mapActions, mapMutations } from 'vuex'

  export default {
    components: { Pager, Modal },
    props: [
      'searchPlaceholder',
      'addPrompt',
      'removeHeader',
      'downloadPrompt',
      'uploadPrompt'
    ],
    data: () => ({ itemId: '', itemTitle: '' }),
    computed: {
      ...mapGetters('items', ['my', 'pageCount', 'page', 'filter'])
    },
    methods: {
      ...mapActions('items',
        ['getItems', 'changePage', 'applyFilter', 'download', 'upload', 'delete']),
      ...mapMutations('notification', ['notify']),
      applySearch () {
        this.applyFilter(this.$refs.search.value.trim())
      },
      clearSearch () {
        this.applyFilter('')
      },
      async uploadChange (event) {
        const files = event.target.files
        if (!files.length) return
        try {
          await this.upload(files[0])
          this.notify({ msg: 'Items have been uploaded :)', type: 'info' })
        } catch (e) {
          this.notify({ msg: 'Something went wrong when uploading items :(', type: 'danger' })
        } finally {
          this.$refs.uploadForm.reset()
        }
      },
      openConfirm ({ _id, title }) {
        this.itemId = _id
        this.itemTitle = title
        this.$refs.deleteConfirm.open()
      },
      async closeConfirm (result) {
        if (!result) return
        try {
          await this.delete(this.itemId)
          this.notify({ msg: 'An item has been removed :)', type: 'info' })
        } catch (e) {
          this.notify({ msg: 'Something went wrong when removing an item :(', type: 'danger' })
        }
      }
    },
    mounted () {
      if (this.my) this.getItems()
      else this.clearSearch()
    }
  }
</script>

<style>
  /*
   * Vertical align text in table
   */
  .table td {
      vertical-align: middle !important;
  }
  /*
   * Glyphicon opacity
   */
  a > i, label > i {
      opacity: 0.5;
  }
  a:hover > i, label:hover > i {
      opacity: 1.0;
  }
  /*
   * Hide file input element
   */
  input[type="file"] {
    width: 0.1px;
    height: 0.1px;
    opacity: 0;
    overflow: hidden;
    position: absolute;
    z-index: -1;
  }
  /*
   * Search bar
   */
  .my-search {
    margin-bottom: 18px;
  }
  /*
   * Table header
   */
  .table > thead > tr > th {
    border-bottom: 0;
    font-weight: normal;
    font-style: italic;
    opacity: 0.6;
  }
</style>

// front-end/src/app/customization/item-list.component.ts
import { Component, Input, OnInit, ViewChild } from '@angular/core';
import { Http, Headers } from '@angular/http';
import { Observable } from 'rxjs';
import { Item } from './item.model';
import { AppConfig } from '../config';
import { AuthService } from '../authentication/auth.service';
import { ModalComponent } from './modal.component';
import { NotificationService } from '../notifications/notification.service';
import { ItemsStateService } from './items-state.service';

const saveAs = require('file-saver/FileSaver.js').saveAs;

@Component({
    selector: 'item-list',
    templateUrl: './item-list.component.html'
})
export class ItemListComponent implements OnInit {

    items: Item[];
    pages: number;

    @Input() state: ItemsStateService;
    @Input() header: string;
    @Input() searchPlaceholder: string;
    @Input() addPrompt: string;
    @Input() uploadPrompt: string;
    @Input() downloadPrompt: string;
    @Input() removeHeader: string;
    @Input() apiSelector: string;
    @Input() exportFileName: string;

    @ViewChild('deleteConfirm') deleteConfirm: ModalComponent;
    @ViewChild('uploadForm') uploadForm: any;

    constructor(
        private http: Http,
        private config: AppConfig,
        private auth: AuthService,
        private ntfs: NotificationService
    ) {}

    ngOnInit() {
        this.pageReset();
    }

    getItems() {
        const url = `${this.config.apiUrl}/${this.apiSelector}`;
        const requestOptions = Object.assign(
            {}, this.auth.authHeader, this.state.queryParams
        );
        this.http.get(url, requestOptions)
        .map(res => {
            const data = res.json();
            data.items.forEach((item: any) => item.completed = new Date(item.completed));
            return data;
        }).subscribe(data => {
            this.items = data.items;
            this.pages = data.pages;
        });
    }

    applySearch(term: string) {
        this.state.term = term;
        this.state.page = 1;
        this.getItems();
    }

    pageChange(page: number) {
        this.state.page = page;
        this.getItems();
    }

    pageReset() {
        this.state.page = 1;
        this.getItems();
    }

    removeConfirm(item: Item) {
        this.deleteConfirm.open(item.title).subscribe(isConfirmed => {
            if(isConfirmed) this.removeBook(item);
         });
    }

    private removeBook(item: Item) {
        const apiUrl = `${this.config.apiUrl}/${this.apiSelector}/${item._id}`;
        this.http
            .delete(apiUrl, this.auth.authHeader)
            .subscribe(res => {
                this.pageReset();
                this.ntfs.notifySuccess('An item has been removed :-)');
            }, err => {
                this.ntfs.notifyDanger('Something went wrong when removing an item :-(');
            });
    }

    /*
     * Date pipe doesn't work in Safari.
     * TO DO: Move to a service.
     */
    formatDate(date: Date) {
        const months = [
            'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
            'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'
        ];
        if(!date) return null;
        const year = date.getFullYear();
        const month = date.getMonth();
        const day = date.getDate();
        return `${months[month]} ${day}, ${year}`;
    }

    download() {
        const url = `${this.config.apiUrl}/${this.apiSelector}`;
        const requestOptions = Object.assign(
            {}, this.auth.authHeader, this.state.searchParams
        );
        this.http.get(url, requestOptions).map(res => res.json()).subscribe(data => {
            const blob = new Blob(
                [JSON.stringify(data.items, this.replaceForDownload, 1)],
                {type: 'application/json'});
            saveAs(blob, this.exportFileName);
        });
     }

    private replaceForDownload(key: string, value: any) {
        if(key === '_id') return undefined;
        if(value === '') return undefined;
        if(key === 'completed') return value.split(/T/)[0];
        return value;
    }

    uploadChange(event: any) {

        const files = event.target.files;
        if(!files.length) return;

        const apiUrl = `${this.config.apiUrl}/${this.apiSelector}/upload`;
        this.uploadRequest(apiUrl, files[0], this.auth.authHeader.headers)
            .then(() => {
                this.pageReset();
                this.ntfs.notifySuccess('Items have been uploaded :-)');
            }, () => {
                this.ntfs.notifyDanger('Something went wrong when uploading items :-(');
            });

        this.uploadForm.nativeElement.reset();
    }

    private uploadRequest(url: string, file: File, headers: Headers) {

        return new Promise((resolve, reject) => {
            var formData: any = new FormData();
            var xhr = new XMLHttpRequest();
            formData.append("upload", file, file.name);

            xhr.onreadystatechange = function () {
                if (xhr.readyState == 4) {
                    if (xhr.status == 200) {
                        resolve(xhr.response);
                    } else {
                        reject(xhr.response);
                    }
                }
            }

            xhr.open("POST", url, true);
            headers.forEach((values, name, headers) => {
                xhr.setRequestHeader(name, values[0]);
            });
            xhr.send(formData);
        });
    }
}

<my-modal #deleteConfirm title={{removeHeader}} submitButtonLabel="Yes" cancelButtonLabel="No">
    <modal-content>
        Are you sure you want to remove <span class="badge">{{deleteConfirm.modalData}}</span>?
    </modal-content>
</my-modal>

<div class="panel panel-default">

    <div class="panel-heading">

        <h4 class="panel-title with-controls pull-left">{{header}}</h4>

        <div class="input-group">

            <input #search (keydown.enter)="applySearch(search.value)" (keydown.esc)="applySearch('')" [value]="state.term" type="text" class="form-control" placeholder={{searchPlaceholder}}>

            <div class="input-group-btn">

                <a (click)="applySearch(search.value)" class="btn btn-default" title="Apply Search Filter"><i class="glyphicon glyphicon-search"></i></a>

                <a (click)="applySearch('')" class="btn btn-default" title="Clear Search Filter"><i class="glyphicon glyphicon-remove-sign"></i></a>

                <a [routerLink]="['new']" class="btn btn-default" title={{addPrompt}}><i class="glyphicon glyphicon-plus"></i></a>

                <a (click)="download()" class="btn btn-default" title="{{downloadPrompt}}"><i class="glyphicon glyphicon-download"></i></a>

                <label for="file" class="btn btn-default" title={{uploadPrompt}}><i class="glyphicon glyphicon-upload"></i></label>

                <form #uploadForm>
                    <input type="file" id="file" (change)="uploadChange($event)">
                </form>

            </div>
        </div>
    </div>

    <ng-content></ng-content>

    <my-pager *ngIf="pages" [pagesCount]="pages" [page]="state.page" (change)="pageChange($event)"></my-pager>

</div>
