// front-end-vue/src/components/Navbar.vue
<template>
  <nav class="navbar navbar-default">
    <div class="container-fluid">

      <div class="navbar-header">
        <router-link active-class="active" to="/home" class="navbar-brand">
          <span class="glyphicon glyphicon-home" aria-hidden="true"></span>
          &nbsp;My Hobbies
        </router-link>
      </div>

      <ul class="nav navbar-nav">
        <router-link tag="li" active-class="active" to="/books">
          <a>
            <span class="glyphicon glyphicon-book" aria-hidden="true"></span>
            &nbsp;Books
          </a>
        </router-link>

        <router-link tag="li" active-class="active" to="/movies">
          <a>
            <span class="glyphicon glyphicon-film" aria-hidden="true"></span>
            &nbsp;Movies
          </a>
        </router-link>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <router-link tag="li" active-class="active" to="/login">
          <a>
            <span class="glyphicon glyphicon-log-in" aria-hidden="true"></span>
            &nbsp;Log in
          </a>
        </router-link>

        <router-link tag="li" active-class="active" to="/register">
          <a>
            <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
            &nbsp;Sign up
          </a>
        </router-link>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <li>
          <a>
            <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
            Logged in as: name email
          </a>
        </li>

        <router-link tag="li" to="/home">
          <a>
            <span class="glyphicon glyphicon-log-out" aria-hidden="true"></span>
            &nbsp;Log out
          </a>
        </router-link>
      </ul>

    </div>
  </nav>
</template>

<style>
  a.active {
    color: #000 !important;
    text-shadow: 2px 2px #ccc;
  }
</style>

// front-end-ng2/src/app/navbar/navbar.component.ts
import { Component } from '@angular/core';
import { AuthService } from '../authentication/auth.service';

@Component({
    selector: 'my-navbar',
    templateUrl: './navbar.component.html'
})
export class NavbarComponent {

    constructor(public auth: AuthService) {}

    logout() {
        this.auth.logout();
    }
}
<nav class="navbar navbar-default">
  <div class="container-fluid">

  <div class="navbar-header">
    <a [routerLink]="['/home']" routerLinkActive="active" class="navbar-brand">
      <span class="glyphicon glyphicon-home" aria-hidden="true"></span>
      &nbsp;My Hobbies
    </a>
  </div>

  <ul *ngIf="auth.isLoggedIn" class="nav navbar-nav">
    <li>
      <a [routerLink]="['/books']" routerLinkActive="active">
        <span class="glyphicon glyphicon-book" aria-hidden="true"></span>
        &nbsp;Books
      </a>
    </li>
    <li>
      <a [routerLink]="['/movies']" routerLinkActive="active">
      <span class="glyphicon glyphicon-film" aria-hidden="true"></span>
      &nbsp;Movies
      </a>
    </li>
  </ul>

  <ul *ngIf="!auth.isLoggedIn" class="nav navbar-nav navbar-right">
    <li>
      <a [routerLink]="['/login']" routerLinkActive="active">
        <span class="glyphicon glyphicon-log-in" aria-hidden="true"></span>
        &nbsp;Log in
      </a>
    </li>
    <li>
      <a [routerLink]="['/register']" routerLinkActive="active">
        <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
        &nbsp;Sign up
      </a>
    </li>
  </ul>

  <ul *ngIf="auth.isLoggedIn" class="nav navbar-nav navbar-right">
    <li>
      <a>
        <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
        Logged in as: <{{auth.currentUser.name}}>{{auth.currentUser.email}}
      </a>
    </li>
    <li>
      <a [routerLink]="['/home']" (click)="logout()">
        <span class="glyphicon glyphicon-log-out" aria-hidden="true"></span>
        &nbsp;Log out
      </a>
    </li>
  </ul>

  </div>
</nav>
