// front-end-vue/src/components/Login.vue
<template>
  <div class="row">
    <div class="col-sm-4 col-sm-offset-4">

      <form @submit.prevent="validateBeforeSubmit">

        <div class="form-group" :class="{ 'has-error': $v.email.$error }">
          <label class="control-label" for="email">Email</label>
          <input id="email"
                 v-model.trim="email"
                 @input="$v.email.$touch()"
                 class="form-control" type="text" placeholder="Email address">
          <p class="text-danger" v-show="$v.email.$error">{{ vmsgEmail }}</p>
        </div>

        <div class="form-group" :class="{ 'has-error': $v.password.$error }">
          <label class="control-label" for="password">Password</label>
          <input id="password"
                 v-model="password"
                 @input="$v.password.$touch()"
                 class="form-control" type="password" placeholder="Password">
          <p class="text-danger" v-show="$v.password.$error">{{ vmsgPassword }}</p>
        </div>

        <button type="submit" class="btn btn-default">
          Log in
        </button>

      </form>

    </div>
  </div>
</template>

<script>
  import vh, { email, password } from '@/helpers/validators'

  export default {
    data () {
      return {
        email: '',
        password: ''
      }
    },
    validations: {
      email: vh.vrules(email),
      password: vh.vrules(password)
    },
    computed: {
      vmsgEmail () { return vh.vmsg(this.$v.email, email) },
      vmsgPassword () { return vh.vmsg(this.$v.password, password) }
    },
    methods: {
      validateBeforeSubmit () {
        this.$v.$touch()
        if (this.$v.$invalid) return
        this.submitForm()
      },
      async submitForm () {
        try {
          await this.$store.dispatch('auth/login', { ...this.$data })
          console.log('OK')
          this.$router.push('/home')
        } catch (e) {
          console.log('ER')
        }
      }
    }
  }
</script>

// front-end/src/app/authentication/login.component.ts
import { Component } from '@angular/core';
import { AuthService } from './auth.service';
import { LoginUser } from './user';
import { EmailValidator } from '../validators/email.validator';
import { PasswordValidator } from '../validators/password.validator';

@Component({
    template: require('./login.component.html'),
    directives: [EmailValidator, PasswordValidator]
})
export class LoginComponent {

    user = new LoginUser();

    constructor(private auth: AuthService) {}

    login() {
        this.auth.login(this.user, '/home');
    }
}

<div class="row">
    <div class="col-sm-4 col-sm-offset-4">

        <form novalidate (ngSubmit)="login()" #loginForm="ngForm">
            <div class="form-group">
                <label for="email">Email</label>
                <input
                    type="text"
                    placeholder="Email address"
                    class="form-control"
                    [(ngModel)]="user.email"
                    validate-email
                    name="email"
                    #email="ngModel">
                <div [hidden]="email.valid || email.pristine" class="alert alert-danger">
                    {{email.errors?.message}}
                </div>
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input
                    type="password"
                    class="form-control"
                    placeholder="Password"
                    [(ngModel)]="user.password"
                    validate-password
                    name="password"
                    #password="ngModel">
                <div [hidden]="password.valid || password.pristine" class="alert alert-danger">
                    {{password.errors?.message}}
                </div>
            </div>
            <button type="submit" [disabled]="!loginForm.valid" class="btn btn-default">
                Log in
            </button>
        </form>

    </div>
</div>
