// front-end/src/app/home/home.component.ts
import { Component } from '@angular/core';

@Component({
    template: `
    <div class="panel panel-default">
      <div class="panel-body">
        <p>
            <b>MY HOBBIES</b>
            is an
            <a href="https://github.com/iurii-kyrylenko/hobbies" target="_blank">open-source project</a>
            for keeping track of books you have read/listened and movies you have watched.
        </p>
        <p>
            After logging in you will be able to:
        </p>
        <ul>
            <li>Add an item (book or movie) to the list.</li>
            <li>Modify an existing item.</li>
            <li>Remove an item.</li>
            <li>Perform search for specific item(s).</li>
            <li>Download items as a file in JSON format.</li>
            <li>Upload items from JSON file.</li>
        </ul>
        <p>
            Your data is not accessible to other users.
        </p>
        <p>
            <b>This site is for demonstartion purposes only: you can loose data at any time.</b>
        </p>
      </div>
    </div>
    `
})
export class HomeComponent {}

// front-end/src/components/Home.vue
<template>
  <div class="panel panel-default">
    <div class="panel-body">
      <p>
          <b>MY HOBBIES</b>
          is an
          <a href="https://github.com/iurii-kyrylenko/hobbies" target="_blank">open-source project</a>
          for keeping track of books you have read/listened and movies you have watched.
      </p>
      <p>
          After logging in you are able to:
      </p>
      <ul>
          <li>Add an item (book or movie) to the list.</li>
          <li>Modify an existing item.</li>
          <li>Remove an item.</li>
          <li>Perform search for specific item(s).</li>
          <li>Download items as a file in JSON format.</li>
          <li>Upload items from JSON file.</li>
      </ul>
      <p>
          Also you have the possibilities to:
      </p>
      <ul>
          <li>Share data with other people.</li>
          <li>Change you personal settings.</li>
      </ul>
      <p>
          Unathorized people can see and download the shared data.
      </p>
      <hr />
      <b>Support</b>
      <p>
        <ul>
          <li>
            Nov 3, 2018: Update to latest versions of Vue.js and other libraries
          </li>
          <li>
            May 25, 2017: Change movie info service from <a href="http://www.omdbapi.com/" target="_blank">OMDb</a> to <a href="https://www.themoviedb.org/" target="_blank">TMDb</a>
          </li>
          <li>
            Apr 24, 2017: Wire up the <a href="http://www.omdbapi.com/" target="_blank">OMDb</a> api service to obtain the movie info
          </li>
        </ul>
      </p>
    </div>
  </div>
</template>
