// front-end-ng2/src/app/notifications/notifier.component.ts
import { Component, OnInit } from '@angular/core';
import { NotificationService} from './notification.service';

@Component({
    selector: 'my-notifier',
    template: `
        <div *ngIf="message" [ngClass]="alertClass" class="alert">
            <button type="button" class="close" (click)="message = null">
                <span aria-hidden="true">&times;</span>
            </button>
            {{message}}
        </div>
    `
})
export class NotifierComponent implements OnInit {

    constructor(private ntfc: NotificationService) {}

    message: string;
    alertClass: string;

    ngOnInit() {
        this.ntfc.notifications$.subscribe(
            (notification) => {
                this.message = notification.message;
                this.alertClass = 'alert-' + notification.type;
            }
        );
    }
}

// front-end/src/components/Notifier.vue
<template>
  <div v-if="message" :class="[alertClass]" class="alert">
      <button type="button" class="close" @click="remove">
          <span aria-hidden="true">&times;</span>
      </button>
      {{ message }}
  </div>
</template>

<script>
  import { mapGetters, mapMutations } from 'vuex'

  export default {
    computed: {
      ...mapGetters('notification', ['message', 'alertClass'])
    },
    methods: {
      ...mapMutations('notification', ['remove'])
    }
  }
</script>
