// front-end/src/app/authentication/register.component.ts
import { Component } from '@angular/core';
import { AuthService } from './auth.service';
import { RegisterUser } from './user';
import { UserNameValidator } from '../validators/username.validator';
import { EmailValidator } from '../validators/email.validator';
import { PasswordValidator } from '../validators/password.validator';
import { ConfirmationValidator } from '../validators/confirmation.validator';
import { ReCaptchaComponent } from './recaptcha.component';
import { AppConfig } from '../config';

@Component({
    template: require('./register.component.html'),
    directives: [
        UserNameValidator,
        EmailValidator,
        PasswordValidator,
        ConfirmationValidator,
        ReCaptchaComponent
    ]
})
export class RegisterComponent {

    user = new RegisterUser();
    passwordConfirmation = '';

    constructor(
        private config: AppConfig,
        private auth: AuthService
    ) {}

    register() {
        this.auth.register(this.user, '/home', this.reset.bind(this));
    }

    getCaptchaResponse(res: string) {
        this.user.captchaResponse = res;
    }

    reset() {
        window['grecaptcha'].reset();
        this.user.captchaResponse = '';
    }
}
<div class="row">
    <div class="col-sm-4 col-sm-offset-4">

        <form novalidate (ngSubmit)="register()" #registerForm="ngForm">

            <div class="form-group">
                <label for="name">Name</label>
                <input
                    type="text"
                    placeholder="User name"
                    class="form-control"
                    [(ngModel)]="user.name"
                    validate-name
                    name="name"
                    #name="ngModel">
                <div [hidden]="name.valid || name.pristine" class="alert alert-danger">
                    {{name.errors?.message}}
                </div>
            </div>

            <div class="form-group">
                <label for="email">Email</label>
                <input
                    type="text"
                    placeholder="Email address"
                    class="form-control"
                    [(ngModel)]="user.email"
                    validate-email
                    name="email"
                    #email="ngModel">
                <div [hidden]="email.valid || email.pristine" class="alert alert-danger">
                    {{email.errors?.message}}
                </div>
            </div>

            <div ngModelGroup #passwordGroup="ngModelGroup" validate-confirmation>
                <div class="form-group">
                    <label for="password">Password</label>
                    <input
                        type="password"
                        placeholder="Password"
                        class="form-control"
                        [(ngModel)]="user.password"
                        validate-password
                        name="password"
                        #password="ngModel">
                    <div [hidden]="password.valid || password.pristine" class="alert alert-danger">
                        {{password.errors?.message}}
                    </div>
                </div>

                <div class="form-group">
                    <label for="confirmation">Confirmation</label>
                    <input
                        type="password"
                        placeholder="Password confirmation"
                        class="form-control"
                        [(ngModel)]="passwordConfirmation"
                        required
                        name="confirmation"
                        #confirmation="ngModel">
                    <div [hidden]="confirmation.valid || confirmation.pristine" class="alert alert-danger">
                        Confirmation is required
                    </div>
                </div>

                <div [hidden]="!passwordGroup.errors" class="alert alert-danger">
                    {{passwordGroup.errors?.message}}
                </div>
            </div>

            <div class="form-group">
                <re-captcha
                    [siteKey]="config.reCaptchaSiteKey"
                    (captchaResponse)="getCaptchaResponse($event)">                        
                </re-captcha>
            </div>

            <button
                type="submit"
                [disabled]="!registerForm.form.valid || !user.captchaResponse"
                class="btn btn-default">
                Sign up
            </button>
        </form>

    </div>
</div>

// front-end-vue/src/components/Register.vue
<template>
  <div class="row">
    <div class="col-sm-4 col-sm-offset-4">

      <form @submit.prevent="validateBeforeSubmit">

        <div class="form-group" :class="{ 'has-error': $v.name.$error }">
          <label class="control-label" for="name">Name</label>
          <input id="name"
                 v-model.trim="name"
                 @input="$v.name.$touch()"
                 class="form-control" type="text" placeholder="User name">
          <p class="text-danger" v-show="$v.name.$error">{{ vmsgName }}</p>
        </div>

        <div class="form-group" :class="{ 'has-error': $v.email.$error }">
          <label class="control-label" for="email">Email</label>
          <input id="email"
                 v-model.trim="email"
                 @input="$v.email.$touch()"
                 class="form-control" type="text" placeholder="Email address">
          <p class="text-danger" v-show="$v.email.$error">{{ vmsgEmail }}</p>
        </div>

        <div class="form-group" :class="{ 'has-error': $v.password.$error }">
          <label class="control-label" for="password">Password</label>
          <input id="password"
                 v-model="password"
                 @input="$v.password.$touch()"
                 class="form-control" type="password" placeholder="Password">
          <p class="text-danger" v-show="$v.password.$error">{{ vmsgPassword }}</p>
        </div>

        <div class="form-group" :class="{ 'has-error': $v.confirmation.$error }">
          <label class="control-label" for="confirmation">Confirmation</label>
          <input id="confirmation"
                 v-model="confirmation"
                 @input="$v.confirmation.$touch()"
                 class="form-control" type="password" placeholder="Password confirmation">
          <p class="text-danger" v-show="$v.confirmation.$error">{{ vmsgConfirmation }}</p>
        </div>

        <div class="form-group">
          <re-captcha
              :siteKey="reCaptchaSiteKey"
              @captchaResponse="getCaptchaResponse">
          </re-captcha>
        </div>

        <button type="submit" class="btn btn-default">
          Sign up
        </button>

      </form>

    </div>
  </div>
</template>

<script>
  import vh, { userName, email, password, confirmation } from '@/helpers/validators'
  import ReCaptcha from './ReCaptcha'
  import config from '@/helpers/config'
  import { mapMutations } from 'vuex'

  const getUser = ({ name, email, password, captchaResponse }) =>
    ({ name, email, password, captchaResponse })

  export default {
    components: { ReCaptcha },
    data () {
      return {
        name: '',
        email: '',
        password: '',
        captchaResponse: '',
        confirmation: '',
        reCaptchaSiteKey: config.reCaptchaSiteKey
      }
    },
    validations: {
      name: vh.vrules(userName),
      email: vh.vrules(email),
      password: vh.vrules(password),
      confirmation: vh.vrules(confirmation)
    },
    computed: {
      vmsgName () { return vh.vmsg(this.$v.name, userName) },
      vmsgEmail () { return vh.vmsg(this.$v.email, email) },
      vmsgPassword () { return vh.vmsg(this.$v.password, password) },
      vmsgConfirmation () { return vh.vmsg(this.$v.confirmation, confirmation) }
    },
    methods: {
      ...mapMutations('notification', ['notify']),
      getCaptchaResponse (res) {
        this.captchaResponse = res
      },
      reset () {
        window['grecaptcha'].reset()
        this.captchaResponse = ''
      },
      validateBeforeSubmit () {
        this.$v.$touch()
        if (this.$v.$invalid || !this.captchaResponse) return
        this.submitForm()
      },
      async submitForm () {
        try {
          await this.$store.dispatch('auth/register', getUser(this.$data))
          this.notify({ msg: 'You have been registered and logged in.', type: 'info' })
          this.$router.push('/home')
        } catch (e) {
          this.reset()
          this.notify({ msg: 'You have failed to register. Try again with another email address.', type: 'danger' })
        }
      }
    }
  }
</script>
